-- Creación de discos
CREATE TABLESPACE TBSP_DATA DATAFILE
'...\oradata\datafiles\TBSP_DATA01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
'...\oradata\datafiles\TBSP_DATA02.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- Creación de temporal   
CREATE TEMPORARY TABLESPACE TBSP_DATA_TMP TEMPFILE
'...\oradata\datafiles\TBSP_DATA_TEMP01.DBF' SIZE 3G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- Creación de esquema y privilegios
CREATE USER [NEW SCHEMA NAME]
  IDENTIFIED BY "[NEW SCHEMA PASSWORD]"
  DEFAULT TABLESPACE TBSP_DATA
  TEMPORARY TABLESPACE TBSP_DATA_TMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for [NEW SCHEMA NAME]
  GRANT CONNECT TO [NEW SCHEMA NAME]
  ALTER USER [NEW SCHEMA NAME] DEFAULT ROLE NONE;
  -- 14 System Privileges for [NEW SCHEMA NAME]
  GRANT CREATE ANY TABLE TO [NEW SCHEMA NAME];
  GRANT CREATE ANY VIEW TO [NEW SCHEMA NAME];
  GRANT CREATE DATABASE LINK TO [NEW SCHEMA NAME];
  GRANT CREATE JOB TO [NEW SCHEMA NAME];
  GRANT CREATE MATERIALIZED VIEW TO [NEW SCHEMA NAME];
  GRANT CREATE PROCEDURE TO [NEW SCHEMA NAME];
  GRANT CREATE PUBLIC SYNONYM TO [NEW SCHEMA NAME];
  GRANT CREATE SEQUENCE TO [NEW SCHEMA NAME];
  GRANT CREATE SESSION TO [NEW SCHEMA NAME];
  GRANT CREATE SYNONYM TO [NEW SCHEMA NAME];
  GRANT CREATE TABLE TO [NEW SCHEMA NAME];
  GRANT CREATE TABLESPACE TO [NEW SCHEMA NAME];
  GRANT CREATE TRIGGER TO [NEW SCHEMA NAME];
  GRANT CREATE VIEW TO [NEW SCHEMA NAME];
  -- 1 Tablespace Quota for [NEW SCHEMA NAME]
  ALTER USER [NEW SCHEMA NAME] QUOTA UNLIMITED ON TBSP_DATA;
  
-- Creación de DBLINK
CREATE PUBLIC DATABASE LINK [DBL_NAME]
CONNECT TO [SCHEMA NAME]
IDENTIFIED BY "[SCHEMA PASSWORD]"
USING '[IP NUMBER]:[PORT]/[SID]';
  